---
title: "Kerry vs Dublin"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "JSwag"
date: "3 March 2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
#Load packages
library(dplyr)
library(deldir)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(knitr)
library(rmarkdown)
library(kableExtra)
library(data.table)
library(RColorBrewer)
library(gridExtra)
library(igraph)
library(tidyverse)
library(treemap)
library(plotly)

pass <- read.csv (file.choose(),sep=";",header=TRUE,check.names=FALSE)
attach (pass)

position <- read.csv (file.choose(),sep=";",header=TRUE,check.names=FALSE)
attach (position)

scores <- read.csv (file.choose(),sep=";",header=TRUE,check.names=FALSE)
attach (scores)

```

```{r}
create_Stats_Pitch <- function(grass_colour, line_colour, background_colour, goal_colour, BasicFeatures){
  
  theme_blankPitch = function(size=12) { 
    theme(
      #axis.line=element_blank(), 
      axis.text.x=element_blank(), 
      axis.text.y=element_blank(), 
      #axis.ticks.y=element_text(size=size),
      #   axis.ticks=element_blank(),
      axis.ticks.length=unit(0, "lines"), 
      #axis.ticks.margin=unit(0, "lines"), 
      axis.title.x=element_blank(), 
      axis.title.y=element_blank(), 
      legend.background=element_rect(fill=background_colour, colour=NA), 
      legend.key=element_rect(colour=background_colour,fill=background_colour), 
      legend.key.size=unit(1.2, "lines"), 
      legend.text=element_text(size=size), 
      legend.title=element_text(size=size, face="bold",hjust=0),
      strip.background = element_rect(colour = background_colour, fill = background_colour, size = .5),
      panel.background=element_rect(fill=background_colour,colour=background_colour), 
      #       panel.border=element_blank(), 
      panel.grid.major=element_blank(), 
      panel.grid.minor=element_blank(), 
      panel.spacing=element_blank(), 
      plot.background=element_blank(), 
      plot.margin=unit(c(0, 0, 0, 0), "lines"), 
      plot.title=element_text(size=size*1.2), 
      strip.text.y=element_text(colour=background_colour,size=size,angle=270),   
      strip.text.x=element_text(size=size*1))}
  
  ymin <- 0.5 # minimum width
  ymax <- 5.5 # maximum width
  xmin <- 0.5 # minimum length
  xmax <- 7.5 # maximum length
  
  # Defining features along the length
  defel <- 0.5
  def14 <- 1.25
  def21 <- 1.5
  def45 <- 2.5
  def65 <- 3.5
  off65 <- 4.5
  off45 <- 5.5
  off21 <- 6.5
  off14 <- 6.75
  offel <- 7.5

  
  # Defining features along the width
  srwing <- 1.5
  frightwing <- 5
  rhalfsp <- 2.5
  ctre <- 3.5
  lhspce <- 4.5
  leftwing <- 5.5
  right14d <- 2.6
  left14d <- 3.4
  
  
  # Defining features along the width
  
  boxEdgeOff <- 6.75  
  boxEdgeLeft <- 2.6 
  boxEdgeRight <- 3.4 
  
  # small sqaure
  
  sixYardDef <- 0.75
  sixYardOff <- 7.25
  sixYardLeft <- 2.70 
  sixYardRight <- 3.3
  
  
  
  if(BasicFeatures == TRUE){
    ## initiate the plot, set some boundries to the plot
    p <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)) +
      # add the theme 
      theme_blankPitch() +
      # add halway line
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) + 
      geom_segment(aes(x = def14, y = ymin, xend = def14, yend = ymax),colour = "white",linetype="solid") +   
      geom_segment(aes(x = def21, y = ymin, xend = def21, yend = ymax),colour = "white",linetype="solid") + 
      geom_segment(aes(x = def45, y = ymin, xend = def45, yend = ymax),colour = "blue",linetype="solid") +
      geom_segment(aes(x = def65, y = ymin, xend = def65, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = off21, y = ymin, xend = off21, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off14, y = ymin, xend = off14, yend = ymax),colour = "white",linetype="solid") + 
      geom_segment(aes(x = xmin, y = right14d, xend = def14, yend = right14d),colour = "white",linetype="solid") + 
      geom_segment(aes(x = xmin, y = left14d, xend = def14, yend = left14d),colour = "white",linetype="solid") +
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") + 
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = rhalfsp, xend = xmax, yend = rhalfsp),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = ctre , xend = xmax, yend = ctre),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = lhspce, xend = xmax, yend = lhspce),colour = line_colour,linetype="dotted") + 
      geom_rect(aes(xmin=boxEdgeOff, xmax=xmax, ymin=boxEdgeLeft, ymax=boxEdgeRight), colour = "white", fill = grass_colour) + 
      geom_rect(aes(xmin=xmin, xmax=sixYardDef, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") +  
      geom_rect(aes(xmin=sixYardOff, xmax=xmax, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") + 
      geom_segment(aes(x = 4, y = 2.90, xend = 4, yend = 3.10),colour = "white") +
      geom_segment(aes(x =0.5, y = 2.75, xend = 0.5, yend = 3.25),colour = "blue", size = 2) +
      geom_segment(aes(x =7.5, y = 2.75, xend = 7.5, yend = 3.25),colour = "black", size = 2) +
      annotate(geom="text", x= 1.50, y=.57, label="21",color = "white") +
      annotate(geom="text", x= 2.50, y=.57, label="45",color = "blue") +
      annotate(geom="text", x= 3.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x= 4.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x=5.50, y=.57, label="45", color="black") +
      annotate(geom="text", x=6.50, y=.57, label="21",color = "white") 
    
  }
  
  else{
    ## initiate the plot, set some boundries to the plot
    p <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin-0.5,ymax+0.5)) +
      # add the theme 
      theme_blankPitch() +
      # add the base rectangle of the pitch 
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = line_colour) +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "Red",linetype="dotted")
    
  }
  
  return(p)}


p <- create_Stats_Pitch("#538032", "#A9A9A9", "#ffffff", "#000000", BasicFeatures=TRUE)



```

```{r}
create_Stats_Pitch <- function(grass_colour, line_colour, background_colour, goal_colour, BasicFeatures){
  
  theme_blankPitch = function(size=12) { 
    theme(
      #axis.line=element_blank(), 
      axis.text.x=element_blank(), 
      axis.text.y=element_blank(), 
      #axis.ticks.y=element_text(size=size),
      #   axis.ticks=element_blank(),
      axis.ticks.length=unit(0, "lines"), 
      #axis.ticks.margin=unit(0, "lines"), 
      axis.title.x=element_blank(), 
      axis.title.y=element_blank(), 
      legend.background=element_rect(fill=background_colour, colour=NA), 
      legend.key=element_rect(colour=background_colour,fill=background_colour), 
      legend.key.size=unit(1.2, "lines"), 
      legend.text=element_text(size=size), 
      legend.title=element_text(size=size, face="bold",hjust=0),
      strip.background = element_rect(colour = background_colour, fill = background_colour, size = .5),
      panel.background=element_rect(fill=background_colour,colour=background_colour), 
      #       panel.border=element_blank(), 
      panel.grid.major=element_blank(), 
      panel.grid.minor=element_blank(), 
      panel.spacing=element_blank(), 
      plot.background=element_blank(), 
      plot.margin=unit(c(0, 0, 0, 0), "lines"), 
      plot.title=element_text(size=size*1.2), 
      strip.text.y=element_text(colour=background_colour,size=size,angle=270),   
      strip.text.x=element_text(size=size*1))}
  
  ymin <- 0.5 # minimum width
  ymax <- 5.5 # maximum width
  xmin <- 4.5 # minimum length
  xmax <- 7.5 # maximum length
  
  # Defining features along the length
  defel <- 0.5
  def21 <- 1.5
  def45 <- 2.5
  def65 <- 3.5
  off65 <- 4.5
  off45 <- 5.5
  off21 <- 6.5
  offel <- 7.5
  
  
  
  # Defining features along the width
  srwing <- 1.5
  frightwing <- 5
  rhalfsp <- 2.5
  ctre <- 3.5
  lhspce <- 4.5
  leftwing <- 5.5
  
  
  if(BasicFeatures == TRUE){
    ## initiate the plot, set some boundries to the plot
    hp <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)) +
      # add the theme 
      theme_blankPitch() +
      # add halway line
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "green",linetype="dotted") +
      geom_segment(aes(x = off21, y = ymin, xend = off21, yend = ymax),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = rhalfsp, xend = xmax, yend = rhalfsp),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = ctre , xend = xmax, yend = ctre),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = lhspce, xend = xmax, yend = lhspce),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x =7.5, y = 2.75, xend = 7.5, yend = 3.25),colour = "green", size = 2) +
      annotate(geom="text", x=5.5, y=.57, label="45", color="green") +
      annotate(geom="text", x=6.5, y=.57, label="21",color = "black")
  }
  
  else{
    ## initiate the plot, set some boundries to the plot
    hp <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin-0.5,ymax+0.5)) +
      # add the theme 
      theme_blankPitch() +
      # add the base rectangle of the pitch 
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = line_colour) +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "Red",linetype="dotted")
    
  }
  
  return(hp)}


hp <- create_Stats_Pitch("#ffffff", "#A9A9A9", "#ffffff", "#000000", BasicFeatures=TRUE)


```

```{r}
create_Stats_Pitch <- function(grass_colour, line_colour, background_colour, goal_colour, BasicFeatures){
  
  theme_blankPitch = function(size=12) { 
    theme(
      #axis.line=element_blank(), 
      axis.text.x=element_blank(), 
      axis.text.y=element_blank(), 
      #axis.ticks.y=element_text(size=size),
      #   axis.ticks=element_blank(),
      axis.ticks.length=unit(0, "lines"), 
      #axis.ticks.margin=unit(0, "lines"), 
      axis.title.x=element_blank(), 
      axis.title.y=element_blank(), 
      legend.background=element_rect(fill=background_colour, colour=NA), 
      legend.key=element_rect(colour=background_colour,fill=background_colour), 
      legend.key.size=unit(1.2, "lines"), 
      legend.text=element_text(size=size), 
      legend.title=element_text(size=size, face="bold",hjust=0),
      strip.background = element_rect(colour = background_colour, fill = background_colour, size = .5),
      panel.background=element_rect(fill=background_colour,colour=background_colour), 
      #       panel.border=element_blank(), 
      panel.grid.major=element_blank(), 
      panel.grid.minor=element_blank(), 
      panel.spacing=element_blank(), 
      plot.background=element_blank(), 
      plot.margin=unit(c(0, 0, 0, 0), "lines"), 
      plot.title=element_text(size=size*1.2), 
      strip.text.y=element_text(colour=background_colour,size=size,angle=270),   
      strip.text.x=element_text(size=size*1))}
  
  ymin <- 0.5 # minimum width
  ymax <- 5.5 # maximum width
  xmin <- 0.5 # minimum length
  xmax <- 7.5 # maximum length
  
  # Defining features along the length
  defel <- 0.5
  def14 <- 1.25
  def21 <- 1.5
  def45 <- 2.5
  def65 <- 3.5
  off65 <- 4.5
  off45 <- 5.5
  off21 <- 6.5
  off14 <- 6.75
  offel <- 7.5
  
  
  
  # Defining features along the width
  srwing <- 1.5
  frightwing <- 5
  rhalfsp <- 2.5
  ctre <- 3.5
  lhspce <- 4.5
  leftwing <- 5.5
  right14d <- 2.6
  left14d <- 3.4
  
  
  # Defining features along the width
  
  boxEdgeOff <- 6.75  
  boxEdgeLeft <- 2.6 
  boxEdgeRight <- 3.4 
  
  # small sqaure
  
  sixYardDef <- 0.75
  sixYardOff <- 7.25
  sixYardLeft <- 2.70 
  sixYardRight <- 3.3
  
  
  
  if(BasicFeatures == TRUE){
    ## initiate the plot, set some boundries to the plot
    wp <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)) +
      # add the theme 
      theme_blankPitch() +
      # add halway line
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) + 
      geom_segment(aes(x = def14, y = ymin, xend = def14, yend = ymax),colour = "black",linetype="solid") +   
      geom_segment(aes(x = def21, y = ymin, xend = def21, yend = ymax),colour = "black",linetype="solid") + 
      geom_segment(aes(x = def45, y = ymin, xend = def45, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = def65, y = ymin, xend = def65, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = off21, y = ymin, xend = off21, yend = ymax),colour = "black",linetype="solid") +
      geom_segment(aes(x = off14, y = ymin, xend = off14, yend = ymax),colour = "black",linetype="solid") + 
      geom_segment(aes(x = xmin, y = right14d, xend = def14, yend = right14d),colour = "black",linetype="solid") + 
      geom_segment(aes(x = xmin, y = left14d, xend = def14, yend = left14d),colour = "black",linetype="solid") +
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") + 
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = rhalfsp, xend = xmax, yend = rhalfsp),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = ctre , xend = xmax, yend = ctre),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = lhspce, xend = xmax, yend = lhspce),colour = line_colour,linetype="dotted") + 
      geom_rect(aes(xmin=boxEdgeOff, xmax=xmax, ymin=boxEdgeLeft, ymax=boxEdgeRight), colour = "black", fill = grass_colour) + 
      geom_rect(aes(xmin=xmin, xmax=sixYardDef, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") +  
      geom_rect(aes(xmin=sixYardOff, xmax=xmax, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") + 
      geom_segment(aes(x = 4, y = 2.90, xend = 4, yend = 3.10),colour = "black") +
      geom_segment(aes(x =0.5, y = 2.75, xend = 0.5, yend = 3.25),colour = "blue", size = 2) +
      geom_segment(aes(x =7.5, y = 2.75, xend = 7.5, yend = 3.25),colour = "black", size = 2) +
      annotate(geom="text", x= 1.50, y=.57, label="21",color = "white") +
      annotate(geom="text", x= 2.50, y=.57, label="45",color = "white") +
      annotate(geom="text", x= 3.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x= 4.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x=5.50, y=.57, label="45", color="white") +
      annotate(geom="text", x=6.50, y=.57, label="21",color = "white") 
    
  }
  
  else{
    ## initiate the plot, set some boundries to the plot
    wp <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin-0.5,ymax+0.5)) +
      # add the theme 
      theme_blankPitch() +
      # add the base rectangle of the pitch 
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = line_colour) +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "Red",linetype="dotted")
    
  }
  
  return(wp)}


wp <- create_Stats_Pitch("#ffffff", "#A9A9A9", "#ffffff", "#000000", BasicFeatures=TRUE)


```


```{r, fig.width = 12, fig.height = 6}
#Starting Line up change to single team

positionA <-position %>% filter (Teamnum == "A") 

p + geom_point(data = positionA, aes(x=Areax, y=Areay, color = "green", shape = Team, size = 2)) +
  theme(plot.title = element_text( size=32, hjust=0)) +
  geom_text_repel(data = positionA, aes(x=Areax, y=Areay,color = "green", label = Player), size = 5) +
theme(legend.position="none")

positionB <-position %>% filter (Teamnum == "B") 

p + geom_point(data = positionB, aes(x=Areax, y=Areay, color = "blue", shape = Team, size = 4)) +
  theme(plot.title = element_text( size=32, hjust=0)) +
  geom_text_repel(data = positionB, aes(x=Areax, y=Areay,color = "blue", label = Player), size = 5) +
theme(legend.position="none")
```

```{r, out.width='50%', fig.show='hold', fig.width = 5, fig.height = 5}

komapA <-filter(pass, Teamnum == "A",Action=="Ko Rec"| Action =="Ko Lost"|Action=="KoBrk Rec"|Action=="KoBrk Lost")

p + geom_point(data = komapA, aes(x=Areax, y=Areay, colour = Action, shape = Action))+
labs(title = "Kick Outs", subtitle = "Team A") +
geom_text_repel(data = komapA, aes(x=Areax, y=Areay, label = plylab, col = Action), size = 3) +
theme(plot.title = element_text(hjust=0.5)) +
theme(plot.subtitle = element_text(hjust=0.5)) +
theme(legend.position="none")

```

```{r}
ggplot(data=scores, aes(x=time, y=score, group=Team)) +
    geom_step(aes(color=Team))+
    geom_point() +
theme_classic() +
geom_text_repel(data = scores, aes(x=time, y=score, label = shotlab, size = 4)) + 
geom_vline(xintercept=17.5, linetype="dotted", color = "green") +
 geom_vline(xintercept=35, linetype="dotted", color = "green") +
  guides(size = FALSE) +
  theme(legend.position="bottom")
```

#Score Worm

```{r, fig.width = 16, fig.height = 10}
wormA <-filter(scores, Teamnum == "A")
wormB <-filter(scores, Teamnum == "B") 

ggplot(data=scores, aes(x=time, y=score, group=Team)) +
    geom_step(data=wormA, aes(x=time, y=score), colour = "yellow", ,size=2) + 
    geom_step(data=wormB, aes(x=time, y=score), colour = "lightblue", ,size=2) + 
    geom_point(data = wormA, shape = 1, size = 4, stroke = 2, colour = "green") +
    geom_point(data = wormB, shape = 1, size = 4, stroke = 2, colour = "blue") +
    theme_classic() + 
    theme(plot.background = element_blank(),
    legend.position="bottom",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(), 
    axis.title.x = element_blank(),
    axis.title.y = element_blank()) +
    geom_text_repel(data = wormA, aes(x=time, y=score, label = shotlab), size = 5, colour = "green", nudge_y = 2, 
    segment.size  = 0.2,  direction = "x", hjust = 1 ) + 
    geom_text_repel(data = wormB, aes(x=time, y=score, label = shotlab), size = 5, colour = "blue", nudge_x = 4, nudge_y = -2, 
    segment.size  = 0.2,  direction = "y", hjust = 1) + 
    guides(size = FALSE) +
    geom_rect(aes(xmin = 0, xmax = 17.5, ymin = -Inf, ymax = Inf),
                   fill = "grey77", alpha = 0.01) +
    geom_rect(aes(xmin = 17.51, xmax = 35, ymin = -Inf, ymax = Inf),
                   fill = "grey71", alpha = 0.01) + 
    geom_rect(aes(xmin = 35.01, xmax = 52.5, ymin = -Inf, ymax = Inf),
                   fill = "grey45", alpha = 0.01) +
    geom_rect(aes(xmin = 52.5, xmax = 73, ymin = -Inf, ymax = Inf),
                   fill = "grey35", alpha = 0.01)

```

