---
title: "Player Stats - Ballymun vs Crokes"

output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, options(knitr.kable.NA = ''))
#Load packages
library(flexdashboard)
library(dplyr)
library(deldir)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(knitr)
library(rmarkdown)
library(kableExtra)
library(data.table)
library(RColorBrewer)
library(gridExtra)
library(igraph)
library(tidyverse)
library(treemap)
library(plotly)
library(networkD3)
library (curl)
library(formattable)
library(yaml)
```

```{r}
pass <- read.csv(file="c:/Users/donag/OneDrive/Spreadsheet fun/PA Analytics/PA Template/muncrk/passmuncrk.csv", header=TRUE, sep=";")
attach (pass)
```

```{r}
create_Stats_Pitch <- function(grass_colour, line_colour, background_colour, goala_colour,goalb_colour, BasicFeatures){
  
  theme_blankPitch = function(size=12) { 
    theme(
      #axis.line=element_blank(), 
      axis.text.x=element_blank(), 
      axis.text.y=element_blank(), 
      #axis.ticks.y=element_text(size=size),
      #   axis.ticks=element_blank(),
      axis.ticks.length=unit(0, "lines"), 
      #axis.ticks.margin=unit(0, "lines"), 
      axis.title.x=element_blank(), 
      axis.title.y=element_blank(), 
      legend.background=element_rect(fill=background_colour, colour=NA), 
      legend.key=element_rect(colour=background_colour,fill=background_colour), 
      legend.key.size=unit(1.2, "lines"), 
      legend.text=element_text(size=size), 
      legend.title=element_text(size=size, face="bold",hjust=0),
      strip.background = element_rect(colour = background_colour, fill = background_colour, size = .5),
      panel.background=element_rect(fill=background_colour,colour=background_colour), 
      #       panel.border=element_blank(), 
      panel.grid.major=element_blank(), 
      panel.grid.minor=element_blank(), 
      panel.spacing=element_blank(), 
      plot.background=element_blank(), 
      plot.margin=unit(c(0, 0, 0, 0), "lines"), 
      plot.title=element_text(size=size*1.2), 
      strip.text.y=element_text(colour=background_colour,size=size,angle=270),   
      strip.text.x=element_text(size=size*1))}
  
  ymin <- 0.5 # minimum width
  ymax <- 5.5 # maximum width
  xmin <- 0.5 # minimum length
  xmax <- 7.5 # maximum length
  
  # Defining features along the length
  defel <- 0.5
  def14 <- 1.25
  def21 <- 1.5
  def45 <- 2.5
  def65 <- 3.5
  off65 <- 4.5
  off45 <- 5.5
  off21 <- 6.5
  off14 <- 6.75
  offel <- 7.5
  
  # Defining features along the width
  srwing <- 1.5
  frightwing <- 5
  rhalfsp <- 2.5
  ctre <- 3.5
  lhspce <- 4.5
  leftwing <- 5.5

  #13 Square & small square
  right14d <- 2.6
  left14d <- 3.4
  
  boxEdgeOff <- 6.75  
  boxEdgeLeft <- 2.6 
  boxEdgeRight <- 3.4 
  
  sixYardDef <- 0.75
  sixYardOff <- 7.25
  sixYardLeft <- 2.70 
  sixYardRight <- 3.3

  sixlinest <- 2.7
  sixlineend <- 3.3
  sixdefx <- 0.75 
  sixoffx <- 7.25 

  #halfway
  hwlinest <- 2.9
  hwlineend <- 3.1
  hwx <- 4


 #Goals

  goallinest <- 2.8
  goallineend <- 3.25
  goaldefx <- 0.5 
  goaloffx <- 7.50 

  

circleFundef <- function(center=c(0,0), diameter=1, npoints=100, start=0, end=2)
  {
    tt <- seq(start*pi, end*pi, length.out=npoints)
    data.frame(x = center[1] + diameter / 2 * cos(tt), 
               y = center[2] + diameter / 2 * sin(tt))
  }
  
  circleFunatt <- function(center=c(0,0), diameter=1, npoints=100, start=0, end=2)
  {
    tt <- seq(start*pi, end*pi, length.out=npoints)
    data.frame(x = center[1] - diameter / 2 * cos(tt), 
               y = center[2] - diameter / 2 * sin(tt))
  }
  #### create semi circle ####
  def_circle <-  circleFundef(c(1.5,3), 1, start=1.5, end=2.5)
  att_circle <-  circleFunatt(c(6.5,3), 1, start=1.5, end=2.5)
  
  
  if(BasicFeatures == TRUE){
    ## initiate the plot, set some boundries to the plot
    p <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)) +
      # add the theme 
      theme_blankPitch() +
      # add halway line
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour,size = 0.5) + 
      geom_segment(aes(x = def14, y = ymin, xend = def14, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +   
      geom_segment(aes(x = def21, y = ymin, xend = def21, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x = def45, y = ymin, xend = def45, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = def65, y = ymin, xend = def65, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = off21, y = ymin, xend = off21, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = off14, y = ymin, xend = off14, yend = ymax),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x = xmin, y = right14d, xend = def14, yend = right14d),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x = xmin, y = left14d, xend = def14, yend = left14d),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x = xmax, y = right14d, xend = off14, yend = right14d),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x = xmax, y = left14d, xend = off14, yend = left14d),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x=xmin,y=sixYardLeft, xend= sixYardDef, yend=sixYardLeft),colour = line_colour,linetype="solid",size = 0.5) +  
      geom_segment(aes(x=xmin,y=sixYardRight, xend= sixYardDef, yend=sixYardRight),colour = line_colour,linetype="solid",size = 0.5) +
      geom_segment(aes(x=xmax, y=sixYardLeft, xend=sixYardOff, , yend=sixYardLeft),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x=xmax, y=sixYardRight, xend=sixYardOff, , yend=sixYardRight),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x=sixdefx, y=sixlinest, xend=sixdefx, , yend=sixlineend),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x=sixoffx, y=sixlinest, xend=sixoffx, , yend=sixlineend),colour = line_colour,linetype="solid",size = 0.5) + 
      geom_segment(aes(x = hwx, y = hwlinest, xend = hwx, yend = hwlineend),colour = line_colour) +
      geom_segment(aes(x =goaldefx, y = goallinest, xend = goaldefx, yend = goallineend),colour = goala_colour, size = 1) +
      geom_segment(aes(x =goaloffx, y = goallinest, xend = goaloffx, yend = goallineend),colour = goalb_colour, size = 1) +
      geom_path(data=def_circle, aes(x,y), colour = line_colour,size = 0.5) +
      geom_path(data=att_circle, aes(x,y), colour = line_colour,size = 0.5) + 
      annotate(geom="text", x= 1.45, y=.57, label="20",color = "white") +
      annotate(geom="text", x= 2.55, y=.57, label="45",color = "blue") +
      annotate(geom="text", x= 3.55, y=.57, label="65",color = "white") +
      annotate(geom="text", x= 4.55, y=.57, label="65",color = "white") +
      annotate(geom="text", x=5.55, y=.57, label="45", color="red") +
      annotate(geom="text", x=6.55, y=.57, label="20",color = "white") +
      annotate(geom="text", x= 2, y=.65, label="witnesstheanalysis.com",color = "white",size = 4, alpha = 0.6) +
      annotate(geom="text", x= 6, y=5.45, label="witnesstheanalysis.com",color = "white",size = 4, alpha = 0.6) +
      annotate("segment", x = 3.5, xend = 4.5, y = 0.75, yend = 0.75, colour = "pink", size=3, alpha=0.6, arrow=arrow())
    
  }
  
  else{
    ## initiate the plot, set some boundries to the plot
       p <- ggplot() + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)) +
      # add the theme 
      theme_blankPitch() +
      # add halway line
      geom_rect(aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill = grass_colour, colour = line_colour) + 
      geom_segment(aes(x = def14, y = ymin, xend = def14, yend = ymax),colour = "white",linetype="solid") +   
      geom_segment(aes(x = def21, y = ymin, xend = def21, yend = ymax),colour = "white",linetype="solid") + 
      geom_segment(aes(x = def45, y = ymin, xend = def45, yend = ymax),colour = "blue",linetype="solid") +
      geom_segment(aes(x = def65, y = ymin, xend = def65, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off65, y = ymin, xend = off65, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off45, y = ymin, xend = off45, yend = ymax),colour = "red",linetype="solid") +
      geom_segment(aes(x = off21, y = ymin, xend = off21, yend = ymax),colour = "white",linetype="solid") +
      geom_segment(aes(x = off14, y = ymin, xend = off14, yend = ymax),colour = "white",linetype="solid") + 
      geom_segment(aes(x = xmin, y = right14d, xend = def14, yend = right14d),colour = "white",linetype="solid") + 
      geom_segment(aes(x = xmin, y = left14d, xend = def14, yend = left14d),colour = "white",linetype="solid") +
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") + 
      geom_segment(aes(x = xmin, y = srwing, xend = xmax, yend = srwing),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = rhalfsp, xend = xmax, yend = rhalfsp),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = ctre , xend = xmax, yend = ctre),colour = line_colour,linetype="dotted") +
      geom_segment(aes(x = xmin, y = lhspce, xend = xmax, yend = lhspce),colour = line_colour,linetype="dotted") + 
      geom_rect(aes(xmin=boxEdgeOff, xmax=xmax, ymin=boxEdgeLeft, ymax=boxEdgeRight), colour = "white", fill = grass_colour) + 
      geom_rect(aes(xmin=xmin, xmax=sixYardDef, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") +  
      geom_rect(aes(xmin=sixYardOff, xmax=xmax, ymin=sixYardLeft, ymax=sixYardRight), fill = grass_colour, colour = "white") + 
      geom_segment(aes(x = 4, y = 2.90, xend = 4, yend = 3.10),colour = "white") +
      geom_segment(aes(x =0.5, y = 2.75, xend = 0.5, yend = 3.25),colour = "blue", size = 2) +
      geom_segment(aes(x =7.5, y = 2.75, xend = 7.5, yend = 3.25),colour = "red", size = 2) +
      geom_path(data=def_circle, aes(x,y), colour = "white",size = 0.5) +
      geom_path(data=att_circle, aes(x,y), colour = "white",size = 0.5) + 
      annotate(geom="text", x= 1.50, y=.57, label="20",color = "white") +
      annotate(geom="text", x= 2.50, y=.57, label="45",color = "blue") +
      annotate(geom="text", x= 3.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x= 4.50, y=.57, label="65",color = "white") +
      annotate(geom="text", x=5.50, y=.57, label="45", color="red") +
      annotate(geom="text", x=6.50, y=.57, label="20",color = "white") +
      annotate("segment", x = 3.5, xend = 4.5, y = 0.75, yend = 0.75, colour = "pink", size=3, alpha=0.6, arrow=arrow())
    
  
  }
  
  return(p)}


p <- create_Stats_Pitch("#A2CD5A", "white", "white", "blue","red", BasicFeatures=TRUE)
```

#Ballymun (All Actions)

## 1 Currie
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "1", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 1: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "1", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 2 Conlon
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "2", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 2: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "2", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 3 Dolan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "3", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 3: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "3", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 4 McMahon
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "4", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 4: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "4", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 5 Keeley
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "5", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 5: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "5", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 6 Young
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "6", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 6: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "6", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 7 Hubbard
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "7", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 7: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "7", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 8 McCarthy
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "8", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 8: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "8", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 9 Elliott
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "9", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 9: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "9", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 10 Whelan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "10", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 10: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "10", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 11 Rock
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "11", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 11: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "11", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 12 Swan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "12", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 12: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "12", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 13 O Donovan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "13", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 13: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "13", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 14 Small
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "14", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 14: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "14", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 15 Byrne
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "15", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 15: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "15", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 30 Furman
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "30", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 30: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "30", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 22 George
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "22", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 22: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "22", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 25 Keating
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "25", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 25: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "25", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 19 Player 19
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "19", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 19: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "A", Player == "19", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

#Crokes (All Actions)

## 1 Nestor
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "1", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 1: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "1", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 22 Nolan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "22", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 22: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "22", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 3 A McGowan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "3", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 3: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "3", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 4 O Shea
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "4", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 4: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "4", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 5 O Connor
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "5", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 5: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "5", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 18 O Carroll
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "18", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 18: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "18", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 7 R McGowan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "7", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 7: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "7", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 8 Dias
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "8", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 8: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "8", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 9 Casey
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "9", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 9: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "9", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 10 Cunningham
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "10", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 10: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "10", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 11 Mannion
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "11", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 11: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "11", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 12 Horan
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "12", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 12: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "12", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 13 Pearson
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "13", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 13: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "13", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 26 Mullin
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "26", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 26: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "26", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 15 Burke
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "15", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 15: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "15", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 28 O Brien
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "28", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 28: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "28", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 14 Williams
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "14", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 14: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "14", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## 25 Fox
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "25", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 25: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "25", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

## Player 20  
```{r,  out.width='50%', fig.show='hold', fig.width = 15, fig.height = 15}
Dub <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "20", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Shot Op"|main == "Scr Op"|main == "Ko Rec"|main == "Fkws"|main == "Fkls")%>%summarize(count=n())
my_theme <- function(){
  theme_light() +
    theme(text = element_text(),  
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 30, color = "gray10"),
          plot.title =  element_text( size = 40,color = "red"))
  }
final_data <- Dub %>% 
  # Calculate -- and format -- the percentage for each channel
  mutate(bar_percentage = sprintf("%.1f%%", 100*(count / sum(.$count)))) %>% 
  # Combine that percentage with the actual value
  mutate(bar_label = paste0(format(count, big.mark = ","), ", ", bar_percentage)) %>% 
  # Remove the "just the percentage" column
  select(-bar_percentage)

total_Actions <- paste0("Player 20: ",
                      format(sum(final_data$count), big.mark = ","))
ggplot(final_data, aes(x = main, y = count)) +
ggtitle("Total Actions", 
          subtitle = total_Actions) +   
  geom_bar(stat = "identity", 
           fill = "lightgreen",    
           width = 0.50) +  
geom_text(aes(label = bar_label, hjust = 0), size = 22,colour ="black") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, max(final_data$count) * 1.3)) +
  my_theme() +
theme(legend.position="none", plot.subtitle =  element_text(size = 30, color = "black"))
Dubden <- pass %>%group_by(Player, main)%>%filter( Teamnum == "B", Player == "20", main == "PW"|main == "Rec Op"|main == "Rec Rs"|main == "Pass Op"|main == "Pass Rs"|main == "Shot Op"|main == "Shot Rs"|main == "Ko Rec"|main == "Fkwns"|main == "Fkws"|main == "Fklns"|main == "Fkls"| main == "Spoil Def" |main == "Spoil Off")
p  +  geom_density_2d(data = Dubden, aes(x=Areax, y=Areay),colour = "blue") +
    geom_point(data = Dubden, aes(x=Areax, y=Areay), colour = "white", shape=19, size = 4)+ 
    theme_classic () +  
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          axis.text.x=element_blank(),
          line = element_blank(),
          legend.position="none")
``` 

